# Generated by Django 5.2.5 on 2025-08-11 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(help_text='Volledige naam van de patiënt', max_length=200)),
                ('telefoonnummer', models.CharField(blank=True, help_text='Contactnummer', max_length=20)),
                ('straat', models.CharField(help_text='Straatnaam en huisnummer', max_length=200)),
                ('postcode', models.CharField(help_text='Postcode', max_length=10)),
                ('plaats', models.CharField(help_text='Woonplaats', max_length=100)),
                ('ophaal_tijd', models.DateTimeField(help_text='Gewenste ophaaltijd')),
                ('bestemming', models.CharField(help_text='Bestemming (ziekenhuis, kliniek, etc.)', max_length=300)),
                ('status', models.CharField(choices=[('nieuw', 'Nieuw verzoek'), ('gepland', 'Gepland'), ('onderweg', 'Onderweg'), ('afgeleverd', 'Afgeleverd'), ('geannuleerd', 'Geannuleerd')], default='nieuw', max_length=20)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
                ('bijgewerkt_op', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patiënt',
                'verbose_name_plural': 'Patiënten',
                'ordering': ['ophaal_tijd'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kenteken', models.CharField(help_text='Kenteken van het voertuig', max_length=10, unique=True)),
                ('merk_model', models.CharField(help_text='Merk en model (bijv. Mercedes Sprinter)', max_length=100)),
                ('max_patienten', models.IntegerField(default=1, help_text='Maximum aantal patiënten')),
                ('heeft_rolstoel_lift', models.BooleanField(default=False, help_text='Geschikt voor rolstoelvervoer')),
                ('status', models.CharField(choices=[('beschikbaar', 'Beschikbaar'), ('onderweg', 'Onderweg'), ('onderhoud', 'Onderhoud'), ('defect', 'Defect')], default='beschikbaar', max_length=20)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Voertuig',
                'verbose_name_plural': 'Voertuigen',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('planner', 'Planner'), ('chauffeur', 'Chauffeur'), ('admin', 'Administrator')], default='chauffeur', max_length=20)),
                ('rijbewijs_nummer', models.CharField(blank=True, help_text='Rijbewijsnummer', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('toegewezen_voertuig', models.ForeignKey(blank=True, help_text='Standaard toegewezen voertuig', null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.vehicle')),
            ],
            options={
                'verbose_name': 'Gebruikersprofiel',
                'verbose_name_plural': 'Gebruikersprofielen',
            },
        ),
    ]
