# Generated by Django 5.2.5 on 2025-08-11 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(help_text="Naam van het tijdblok (bijv. 'Ochtend blok 1')", max_length=100)),
                ('heen_start_tijd', models.TimeField(help_text='Start tijd voor ophalen patiënten')),
                ('heen_eind_tijd', models.TimeField(help_text='Eind tijd voor ophalen patiënten')),
                ('terug_start_tijd', models.TimeField(help_text='Start tijd voor terugbrengen patiënten')),
                ('terug_eind_tijd', models.TimeField(help_text='Eind tijd voor terugbrengen patiënten')),
                ('max_rijtijd_minuten', models.IntegerField(default=60, help_text='Maximale rijtijd in minuten')),
                ('max_patienten_per_rit', models.IntegerField(default=4, help_text='Maximum aantal patiënten per rit')),
                ('actief', models.BooleanField(default=True, help_text='Is dit tijdblok actief voor planning?')),
                ('dag_van_week', models.CharField(choices=[('maandag', 'Maandag'), ('dinsdag', 'Dinsdag'), ('woensdag', 'Woensdag'), ('donderdag', 'Donderdag'), ('vrijdag', 'Vrijdag'), ('zaterdag', 'Zaterdag'), ('zondag', 'Zondag'), ('alle_dagen', 'Alle dagen')], default='alle_dagen', max_length=20)),
            ],
            options={
                'verbose_name': 'Tijdblok',
                'verbose_name_plural': 'Tijdblokken',
                'ordering': ['heen_start_tijd'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='eind_behandel_tijd',
            field=models.DateTimeField(blank=True, help_text='Tijd wanneer laatste behandeling eindigt', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='toegewezen_voertuig',
            field=models.ForeignKey(blank=True, help_text='Toegewezen voertuig voor transport', null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.vehicle'),
        ),
        migrations.AddField(
            model_name='patient',
            name='toegewezen_tijdblok',
            field=models.ForeignKey(blank=True, help_text='Toegewezen tijdblok voor planning', null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.timeslot'),
        ),
    ]
