# Generated by Django 5.2.4 on 2025-08-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_timeslot_patient_eind_behandel_tijd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='totaal_zitplaatsen',
            field=models.IntegerField(default=7, help_text='Totaal aantal zitplaatsen (inclusief chauffeur)'),
        ),
    ]
