# Generated by Django 5.2.4 on 2025-08-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_vehicle_totaal_zitplaatsen'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS Breedtegraad', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS Lengtegraad', null=True),
        ),
    ]
