# Generated by Django 5.2.5 on 2025-08-14 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_patient_latitude_patient_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bringen_tijdblok',
            field=models.ForeignKey(blank=True, help_text='Tijdblok voor terugbrengen (naar huis)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bringen_patienten', to='planning.timeslot'),
        ),
        migrations.AddField(
            model_name='patient',
            name='halen_tijdblok',
            field=models.ForeignKey(blank=True, help_text='Tijdblok voor ophalen (naar reha)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halen_patienten', to='planning.timeslot'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='toegewezen_tijdblok',
            field=models.ForeignKey(blank=True, help_text='Toegewezen tijdblok voor planning (DEPRECATED - gebruik halen/bringen)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.timeslot'),
        ),
    ]
