# Generated by Django 5.2.5 on 2025-08-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_patient_bringen_tijdblok_patient_halen_tijdblok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='kleur',
            field=models.CharField(default='#3498db', help_text='Kleur voor dit voertuig (hex code, bijv. #FF5733)', max_length=7),
        ),
    ]
