# Generated by Django 5.2.5 on 2025-08-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_vehicle_kleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='geocoding_notes',
            field=models.TextField(blank=True, help_text='Notities over geocoding problemen of wijzigingen'),
        ),
        migrations.AddField(
            model_name='patient',
            name='geocoding_status',
            field=models.CharField(choices=[('pending', 'Nog niet geocoded'), ('success', 'Succesvol geocoded'), ('failed', 'Adres niet gevonden'), ('manual', 'Handmatig ingevoerd'), ('default', 'Standaard locatie gebruikt')], default='pending', help_text='Status van adres geocoding', max_length=20),
        ),
    ]
