# Generated by Django 5.2.4 on 2025-08-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_patient_geocoding_notes_patient_geocoding_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mobile_notification_sent',
            field=models.DateTimeField(blank=True, help_text='Wanneer is de laatste notificatie naar de chauffeur gestuurd?', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mobile_status',
            field=models.CharField(choices=[('pending', 'Wacht op chauffeur'), ('notified', 'Chauffeur geïnformeerd'), ('in_transit', 'In transit (oranje)'), ('completed', 'Voltooid (groen)')], default='pending', help_text='Status voor mobile app notificaties', max_length=20),
        ),
    ]
