# Generated by Django 5.2.4 on 2025-08-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_patient_mobile_notification_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='heeft_rolstoel_lift',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='max_patienten',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='totaal_zitplaatsen',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='aantal_zitplaatsen',
            field=models.IntegerField(default=7, help_text='Aantal normale zitplaatsen'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='foto',
            field=models.ImageField(blank=True, help_text='Profiel foto van het voertuig', null=True, upload_to='vehicles/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='km_kosten_per_km',
            field=models.DecimalField(decimal_places=2, default=0.29, help_text='Kosten per kilometer', max_digits=5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='maximale_rit_tijd',
            field=models.IntegerField(default=3600, help_text='Maximale rit tijd in seconden'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='referentie',
            field=models.CharField(blank=True, help_text='Unieke referentie (bijv. W206)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='speciale_zitplaatsen',
            field=models.IntegerField(default=0, help_text='Aantal speciale zitplaatsen (rolstoel, etc.)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='merk_model',
            field=models.CharField(help_text='Merk en model (bijv. VW Transporter)', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('beschikbaar', 'Beschikbaar'), ('in_onderhoud', 'In onderhoud'), ('niet_beschikbaar', 'Niet beschikbaar')], default='beschikbaar', max_length=20),
        ),
    ]
