# Generated by Django 5.2.4 on 2025-08-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_remove_vehicle_heeft_rolstoel_lift_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Configuratie sleutel', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Configuratie waarde')),
                ('description', models.TextField(blank=True, help_text='Beschrijving van deze instelling')),
                ('is_active', models.BooleanField(default=True, help_text='Of deze instelling actief is')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuratie',
                'verbose_name_plural': 'Configuraties',
                'ordering': ['key'],
            },
        ),
    ]
