# Generated by Django 5.2.4 on 2025-08-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Naam van de locatie', max_length=100)),
                ('location_type', models.CharField(choices=[('home', 'Home/Depot (Reha Center)'), ('depot', 'Depot'), ('office', 'Kantoor'), ('other', 'Anders')], default='home', help_text='Type locatie', max_length=20)),
                ('address', models.TextField(help_text='Volledig adres')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude (breedtegraad)', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude (lengtegraad)', max_digits=9)),
                ('is_active', models.BooleanField(default=True, help_text='Of deze locatie actief is')),
                ('is_default', models.BooleanField(default=False, help_text='Standaard locatie voor routes')),
                ('description', models.TextField(blank=True, help_text='Beschrijving van de locatie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Locatie',
                'verbose_name_plural': 'Locaties',
                'ordering': ['location_type', 'name'],
            },
        ),
    ]
