# Generated by Django 5.2.4 on 2025-08-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=9, help_text='Latitude (breedtegraad)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=9, help_text='Longitude (lengtegraad)', max_digits=12),
        ),
    ]
