# Generated by Django 5.2.4 on 2025-08-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='rolstoel',
            field=models.BooleanField(default=False, help_text='Heeft patiënt een rolstoel nodig?'),
        ),
    ]
