# Generated by Django 5.2.4 on 2025-08-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_patient_rolstoel'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='default_selected',
            field=models.BooleanField(default=False, help_text='Standaard geselecteerd op planning pagina?'),
        ),
    ]
