# Generated by Django 5.2.4 on 2025-08-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0015_notificationsettings_csvimportlog_planningsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVParserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(help_text="Naam van het CSV formaat (bijv. 'Fahrdlist', 'Routemeister')", max_length=100)),
                ('actief', models.BooleanField(default=True, help_text='Of dit formaat actief is voor detectie')),
                ('prioriteit', models.IntegerField(default=1, help_text='Prioriteit voor detectie (hogere nummer = hogere prioriteit)')),
                ('bestandsnaam_patroon', models.CharField(blank=True, help_text="Regex patroon voor bestandsnaam detectie (bijv. 'fahrdlist.*\\.csv')", max_length=200)),
                ('header_keywords', models.TextField(blank=True, help_text="Komma-gescheiden keywords voor header detectie (bijv. 'kunde,termin,fahrer')")),
                ('kolom_mapping', models.JSONField(default=dict, help_text='JSON mapping van veldnamen naar kolom indices')),
                ('datum_formaten', models.TextField(blank=True, help_text="Komma-gescheiden datum formaten (bijv. 'DD-MM-YYYY,DD.MM.YYYY')")),
                ('tijd_formaten', models.TextField(blank=True, help_text="Komma-gescheiden tijd formaten (bijv. 'HHMM,HH:MM')")),
                ('beschrijving', models.TextField(blank=True, help_text='Beschrijving van het CSV formaat')),
                ('gemaakt_op', models.DateTimeField(auto_now_add=True)),
                ('bijgewerkt_op', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CSV Parser Configuratie',
                'verbose_name_plural': 'CSV Parser Configuraties',
                'ordering': ['-prioriteit', 'naam'],
            },
        ),
    ]
