# Generated by Django 5.2.4 on 2025-08-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0016_csvparserconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningsession',
            name='max_route_time',
            field=models.IntegerField(default=60, help_text='Maximale reistijd per route in minuten'),
        ),
        migrations.AddField(
            model_name='planningsession',
            name='use_google_maps',
            field=models.BooleanField(default=True, help_text='Gebruik Google Maps voor echte routes'),
        ),
        migrations.AddField(
            model_name='planningsession',
            name='validation_errors',
            field=models.JSONField(default=list, help_text='Validatie fouten'),
        ),
        migrations.AddField(
            model_name='planningsession',
            name='validation_warnings',
            field=models.JSONField(default=list, help_text='Validatie waarschuwingen'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status_until',
            field=models.DateField(blank=True, help_text='Status geldig tot (voor onderhoud/reparatie)', null=True),
        ),
        migrations.AlterField(
            model_name='planningsession',
            name='status',
            field=models.CharField(choices=[('concept', 'Concept'), ('processing', 'Verwerking'), ('completed', 'Voltooid'), ('published', 'Gepubliceerd'), ('archived', 'Gearchiveerd')], default='concept', help_text='Status van de planning', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('beschikbaar', 'Beschikbaar'), ('onderhoud', 'Onderhoud'), ('niet_beschikbaar', 'Niet beschikbaar'), ('defect', 'Defect'), ('in_reparatie', 'In reparatie')], default='beschikbaar', max_length=20),
        ),
    ]
