# Generated by Django 5.2.4 on 2025-08-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0017_planningsession_max_route_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Naam van de constraint', max_length=100)),
                ('description', models.TextField(help_text='Beschrijving van wat de constraint doet')),
                ('constraint_type', models.CharField(choices=[('vehicle_capacity', 'Voertuig Capaciteit'), ('vehicle_special_capacity', 'Voertuig Speciale Capaciteit'), ('vehicle_drive_time', 'Voertuig Rijtijd'), ('distance_cost', 'Afstand Kosten'), ('preferred_vehicle', 'Voorkeurs Voertuig'), ('drv_count', 'DRV Aantal')], help_text='Type constraint', max_length=50)),
                ('weight', models.CharField(choices=[('HARD', 'Hard Constraint'), ('SOFT', 'Soft Constraint')], default='HARD', help_text='Hard = mag niet overtreden, Soft = optimalisatie', max_length=10)),
                ('penalty', models.IntegerField(default=1000, help_text='Penalty waarde voor constraint violation')),
                ('is_active', models.BooleanField(default=True, help_text='Of deze constraint actief is')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Extra parameters voor de constraint (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Planning Constraint',
                'verbose_name_plural': 'Planning Constraints',
                'ordering': ['constraint_type', 'name'],
            },
        ),
    ]
