# Generated by Django 5.2.4 on 2025-08-27 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0018_planningconstraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['tijdblok_type', 'aankomst_tijd'], 'verbose_name': 'Tijdblok', 'verbose_name_plural': 'Tijdblokken'},
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='heen_eind_tijd',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='heen_start_tijd',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='max_patienten_per_rit',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='terug_eind_tijd',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='terug_start_tijd',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='aankomst_tijd',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Tijd van aankomst reha center (halen) of eind tijd voor brengen (brengen)'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='tijdblok_type',
            field=models.CharField(choices=[('halen', 'Halen'), ('brengen', 'Brengen')], default='halen', help_text='Type tijdblok', max_length=10),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='naam',
            field=models.CharField(help_text="Naam van het tijdblok (bijv. '08:00 Uhr')", max_length=100),
        ),
    ]
