# Generated by Django 5.2.4 on 2025-08-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0019_alter_timeslot_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMapsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, help_text='Google Maps API Key', max_length=200)),
                ('enabled', models.BooleanField(default=False, help_text='Google Maps API inschakelen')),
                ('distance_weight', models.IntegerField(default=70, help_text='Gewicht voor afstand optimalisatie (0-100)')),
                ('time_weight', models.IntegerField(default=30, help_text='Gewicht voor tijd optimalisatie (0-100)')),
                ('vehicle_utilization_weight', models.IntegerField(default=50, help_text='Gewicht voor voertuig bezetting (0-100)')),
                ('vehicle_optimization', models.CharField(choices=[('max_capacity', 'Maximale bezetting'), ('balanced', 'Evenwichtige verdeling'), ('min_vehicles', 'Minimaal aantal voertuigen'), ('hybrid', 'Hybride aanpak')], default='hybrid', help_text='Strategie voor voertuig optimalisatie', max_length=20)),
                ('daily_api_limit', models.IntegerField(default=1000, help_text='Dagelijks API call limiet')),
                ('monthly_api_limit', models.IntegerField(default=25000, help_text='Maandelijks API call limiet')),
                ('show_loading_timer', models.BooleanField(default=True, help_text='Toon loading timer tijdens route berekening')),
                ('real_time_updates', models.BooleanField(default=True, help_text='Real-time updates bij wijzigingen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Maps Configuratie',
                'verbose_name_plural': 'Google Maps Configuraties',
            },
        ),
        migrations.CreateModel(
            name='GoogleMapsAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.CharField(choices=[('distance_matrix', 'Distance Matrix'), ('directions', 'Directions'), ('geocoding', 'Geocoding')], max_length=50)),
                ('calls_made', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Google Maps API Log',
                'verbose_name_plural': 'Google Maps API Logs',
                'unique_together': {('api_type', 'date')},
            },
        ),
    ]
